config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  root "welcome#index"
  get "/my_portfolio", to: "users#my_portfolio"
  get "/my_friends", to: "users#my_friends"
  get "/search_stock", to: "stocks#search"
  get "/search_friend", to: "users#search"
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:publishable_token],
      secret_token: Rails.application.credentials.iex_client[:secret_token],
      endpoint: 'https://cloud.iexapis.com/v1'
    )
    begin
      new(name: client.company(ticker_symbol).company_name, ticker: ticker_symbol, last_price: client.quote(ticker_symbol).latest_price)
    rescue => exception
      nil
    end
  end

  def self.check_db(ticker_symbol) 
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 9
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name 
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymus"
  end

  def self.search(param)
    param.strip!
    result = where("email like ?", "%#{param}%").or(where("first_name like ?", "%#{param}%").or(where("last_name like ?", "%#{param}%")))
    return nil if result.empty?
    result
  end

  def friend?(user)
    self.friends.where(id: user.id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    Friendship.create(user_id: current_user.id, friend_id: params[:friend])
    flash[:notice] = "Friend was succesfully added to your friends."
    redirect_to my_friends_path
  end

  def destroy 
    friendship = Friendship.where(user_id: current_user.id, friend_id: params[:id]).first
    friendship.destroy 
    flash[:notice] = "Friend was succesfully remove to your friends."
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController 
  def search 
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      @tracked_stocks = current_user.stocks
      if @stock
        render "users/my_portfolio"
      else
        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock was succesfully added to your portfolio."
    redirect_to my_portfolio_path
  end

  def destroy 
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy 
    flash[:notice] = "Stock was succesfully remove to your portfolio."
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends 
    @my_friends = current_user.friends
  end

  def search 
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @my_friends = current_user.friends
      if @friends
        @friends = @friends.select {|friend| current_user.id != friend.id}
        render "users/my_friends"
      else
        flash[:alert] = "No friends found"
        redirect_to my_friends_path
      end
    else
      flash[:alert] = "Please enter a name or email to search"
      redirect_to my_friends_path
    end
  end

  def show 
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row mt-3">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @my_friends.each do |friend| %>
          <tr>
            <td><%= friend.email %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td>
              <%= link_to "View Profile", user_path(friend), class: "btn btn-info btn-sm me-2"%>
              <%= link_to "Stop Following", friendship_path(friend), class: "btn btn-danger btn-sm", data: {turbo_method: "delete", turbo_confirm: "Are you sure?"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/friends/_result.html.erb
<% if @friends %>
  <div class="card card-header d-inline-block">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.first_name ? friend.first_name : "Anonymus" %></td>
            <td><%= friend.email %></td>
            <td>
              <%= link_to "View Profile", user_path(friend), class: "btn btn-info"%>
              <% if !current_user.friend?(friend) %>
                <%= link_to "Follow", friendships_path(friend: friend.id), class: "btn btn-info", data: {turbo_method: "post"}%>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <%= link_to "FinanceTracker", root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link #{'active' if request.path == my_portfolio_path}" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Friends", my_friends_path, class: "nav-link #{'active' if request.path == my_portfolio_path}" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mt-1 me-2">
            <%= current_user.full_name %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, class: "btn btn-danger" , data: {turbo_method: "delete"} %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row mt-3">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <td><strong><%= stock.ticker %></strong></td>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user.id == @user.id %>
                <%= link_to "Remove", user_stock_path(stock), class: "btn btn-danger btn-sm", data: {turbo_method: "delete", turbo_confirm: "Are you sure?"} %>
              <% end %> 
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="card card-header d-inline-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success", data: {turbo_method: "post"}%>
    <% end %>
  </div>
<% end %>

app/views/users/my_friends.html.erb
<h1>My Portfolio</h1>

<div class="search-area mb-3">
  <h3>Search Friends</h3>
  <%= form_with(url: search_friend_path, method: :get) do |f| %>
    <div class="form-group row">
      <div class="col-sm-9">
        <%= f.text_field :friend, placeholder: "Enter name or email", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3">
        <%= f.submit "Search", class: "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

<%= render "friends/result" %>

<% if !@my_friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area mb-3">
  <h3>Search Stocks</h3>
  <%= form_with(url: search_stock_path, method: :get) do |f| %>
    <div class="form-group row">
      <div class="col-sm-9">
        <%= f.text_field :stock, placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3">
        <%= f.submit "Search", class: "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">

</div>

<%= render "users/result" %> 

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header d-inline-block">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.first_name ? @user.first_name : "Anonymus" %></td>
        <td><%= @user.email %></td>
        <td>
          <% if !current_user.friend?(@user) %>
            <%= link_to "Follow", friendships_path(friend: @user.id), class: "btn btn-info", data: {turbo_method: "post"}%>
          <% else %>
            <%= link_to "Stop Following", friendship_path(@user), class: "btn btn-danger btn-sm", data: {turbo_method: "delete", turbo_confirm: "Are you sure?"} %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p>This user is not tracking any stock</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Log out", destroy_user_session_path, data: {turbo_method: "delete"} %>